### ISSUE TITLE
comment

### ISSUE THREAD

**Issue by arademaker** [arnomoonens/fcg-reflexive-phrase#1]
Hi, I am very interested in both topics: basic-fcg and Babel2. You mentioned that this work is part of an assigment of the course 'Artificial Intelligence Programming Paradigms'. Can you tell me more about this course? Link to the homepage? I would really like to have reference about the used material and books.

I found this website:

https://ai.vub.ac.be/courses/2013-2014/artificial-intelligence-programming-paradigms

Is that one?

**Comment by arnomoonens** [comment]
That is indeed the (old) homepage of the course, an updated version can be found [here](https://ai.vub.ac.be/courses/2015-2016/artificial-intelligence-programming-paradigms). To get started with Fluid Construction Grammar (FCG), you need the the [Babel2 framework](http://emergent-languages.org/Babel2/index.html). Tutorials, demonstrations, etc. can be found at the [homepage of FCG](https://www.fcg-net.org/) itself. Good luck!
